### ISSUE TITLE
Linux Mint 20 (Stable release) EFI GRUB menu decorations missing

### ISSUE THREAD

**Issue by DaveBlack** [linuxmint/mint-live-session#1]
**- Issue**
Appears the wonderful EFI GRUB menu decorations are absent in Linux Mint 20 Cinnamon (Stable release), missing from live session, and after installation.

**EFI GRUB menu - live session compare**
![Linux Mint live session EFI boot compare](https://user-images.githubusercontent.com/13056699/85921194-6ea04080-b872-11ea-9324-1507b20b07f0.png)

Update:
Also checked MATE and Xfce (Stable release) live sessions.

@clefebvre Thank you.

**Comment by Dmitry-Eremeev** [comment]
FYI 
LMDE 4 does not have the issue.

**Comment by clefebvre** [comment]
It was removed for compatibility reasons after users reported they were unable to boot.

The user guide has a section dedicated to theming the menu: https://linuxmint-user-guide.readthedocs.io/en/latest/grub.html#how-to-theme-the-grub-menu.
